services:
  slskd:
    image: mpa403/slskd-eg:latest
    container_name: slskd-eg
    restart: unless-stopped
    ports:
      - "5030:5030"  # HTTP
      - "5031:5031"  # HTTPS
      - "50300:50300"  # Soulseek
    volumes:
      - ./slskd_data/config/slskd.yml:/app/slskd.yml:Z
      - ./slskd_data/data:/app/data:z
      - ./slskd_data/downloads:/app/downloads:z
      - ./slskd_data/uploads:/app/uploads:z
    env_file:
      - .env
    environment:
      - SLSKD_HTTP_PORT=5030
      - SLSKD_HTTPS_PORT=5031
      - SLSKD_SLSK_LISTEN_PORT=50300
      - SLSKD_APP_DIR=/app
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_USERNAME=${SLSKD_USERNAME}
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}

    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:${SLSKD_HTTP_PORT:-5030}/health"]
      interval: 60s
      timeout: 3s
      start_period: 60m
      retries: 3
