version: '3.8'
services:
  slskd:
    build: .
    container_name: slskd
    restart: unless-stopped
    ports:
      - "5030:5030"  # HTTP
      - "5031:5031"  # HTTPS
      - "50300:50300"  # Soulseek
    volumes:
      - ./config/slskd.yml:/app/slskd.yml:Z
      - slskd_data:/app/data
    environment:
      - SLSKD_HTTP_PORT=5030
      - SLSKD_HTTPS_PORT=5031
      - SLSKD_SLSK_LISTEN_PORT=50300
      - SLSKD_APP_DIR=/app
      - SLSKD_REMOTE_CONFIGURATION=true
#      - SLSKD_SLSK_USERNAME=eg403
#      - SLSKD_SLSK_PASSWORD=wanker12
#      - SLSKD_UMASK=0022
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5030/health"]
      interval: 60s
      timeout: 3s
      start_period: 60m
      retries: 3

volumes:
  slskd_data:
